### ISSUE TITLE
Let's copy a signup flow as that makes devs like Ben happy

### ISSUE THREAD

**Issue by rod11** [npm/email-templates#16]

**Comment by bcoe** [comment]
<img width="692" alt="screen shot 2015-11-18 at 10 37 54 am" src="https://cloud.githubusercontent.com/assets/194609/11250498/92d1b31e-8de1-11e5-86b6-b0ad86653d11.png">

I think most importantly it would be great to add two npm docs pages:

1. a general installation page, this would outline all the install options and how to run them.
2. a quick start page that gets someone publishing their first module in a minimal number of steps.

**Comment by nexdrew** [comment]
Reopening since #17 was reverted.

**Comment by nexdrew** [comment]
Fixed by #21.

For quickstart doc changes, see npm/docs#496.

For install doc changes, see npm/docs#541.

**Comment by ashleygwilliams** [comment]
question re: this => do we have user research that suggests that Ben is a target demographic? how was this decision made?
